### ISSUE TITLE
DC dimming not working.

### ISSUE THREAD

**Issue by liuwang97** [OnePlusOSS/android_kernel_oneplus_sm8150#2]
DC dimming source code does not seem to be included in your source.
Please provide the full source code per the gpl. thanks @hecaiqiang

**Comment by sekaiacg** [comment]
同上，DC调光相关代码并没有开源。
希望快点更新！！！

**Comment by xiangfeidexiaohuo** [comment]
Yes，Please provide the DC dimming source code！

请提供DC调光部分的源码，实验室里的DC调光不起作用。

**Comment by aaronqiuchiu** [comment]
https://github.com/OnePlusOSS/android_kernel_oneplus_sm8150/commit/ac878e6b24095da39687ba8d6a44cce21ea2a44d
release done
