### ISSUE TITLE
Unified Kernel source for 5G

### ISSUE THREAD

**Issue by nekromantik-zz** [OnePlusOSS/android_kernel_oneplus_sm8150#3]
Hi
I was told the kernel source code for Oneplus 7 Pro and Pro 5G will be unified but there are 2 different branches currently. Will these be unified or stay in seperate branches? Reason I ask is Devs for custom kernels will not like to manage 2 different versions so those of us with 5G wont have option for custom kernel. 
Thanks

**Comment by aaronqiuchiu** [comment]
Hi,
Thank you for your attention. We will use different branch to distinguish between 4G and 5G products.
Thank you very much
