### ISSUE TITLE
I needed to add this include to get everything to compile

### ISSUE THREAD

**Issue by kkuehl** [OnePlusOSS/android_kernel_oneplus_sm8150#5]
From 31bc9c14a6cf930f377bbaa5a7dd29bb7bc22c38 Mon Sep 17 00:00:00 2001
From: Kirby Kuehl <kkuehl@gmail.com>
Date: Wed, 31 Jul 2019 14:15:23 -0700
Subject: [PATCH] fix compilation.

---
 arch/arm64/boot/dts/qcom/sm8150-pmic-overlay.dtsi | 1 +
 1 file changed, 1 insertion(+)

diff --git a/arch/arm64/boot/dts/qcom/sm8150-pmic-overlay.dtsi b/arch/arm64/boot/dts/qcom/sm8150-pmic-overlay.dtsi
index db5573be3eb0..ebdee25e79bf 100644
--- a/arch/arm64/boot/dts/qcom/sm8150-pmic-overlay.dtsi
+++ b/arch/arm64/boot/dts/qcom/sm8150-pmic-overlay.dtsi
@@ -15,6 +15,7 @@
 #include "pm8150b.dtsi"
 #include "pm8150l.dtsi"
 #include <dt-bindings/pinctrl/qcom,pmic-gpio.h>
+#include <dt-bindings/gpio/gpio.h>
 
 /* PMIC GPIO pin control configurations: */
 &pm8150_gpios {
-- 
2.17.1

**Comment by hecaiqiang** [comment]
Hi Kuehl,
This is the PMIC dtsi, it can build pass by include dt-bindings/pinctrl/qcom,pmic-gpio.h, do you add other gpio configuration in your local build code.
Best Regards.
